// <auto-generated />
using System;
using Billing_System.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Billing_System.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Billing_System.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<string>("Mobile")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Pan")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Billing_System.Models.ExchangeLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DeductionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GrossWeightG")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<decimal>("NetWeightG")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("PurityKarat")
                        .HasColumnType("int");

                    b.Property<decimal>("RatePerGramUsed")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("ExchangeLines");
                });

            modelBuilder.Entity("Billing_System.Models.GoldRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Buyback18KPerGram")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Buyback22KPerGram")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Buyback24KPerGram")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EffectiveAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Rate18KPerGram")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Rate22KPerGram")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Rate24KPerGram")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SilverRatePerGram")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EffectiveAt");

                    b.ToTable("GoldRates");
                });

            modelBuilder.Entity("Billing_System.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("GoldRateId")
                        .HasColumnType("int");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GstAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GstRate")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("OldGoldDeduction")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("GoldRateId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("Billing_System.Models.InvoiceLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(240)
                        .HasColumnType("nvarchar(240)");

                    b.Property<decimal>("GrossWeightG")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("GstAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<decimal>("LineSubtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MakingCharge")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MetalValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetWeightG")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("PurityKarat")
                        .HasColumnType("int");

                    b.Property<decimal>("RatePerGramUsed")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("StockTagId")
                        .HasColumnType("int");

                    b.Property<decimal>("StoneAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StoneWeightG")
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("WastageG")
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("StockTagId");

                    b.ToTable("InvoiceLines");
                });

            modelBuilder.Entity("Billing_System.Models.StockTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GrossWeightG")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("Hsn")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<decimal>("MakingChargeRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MakingChargeType")
                        .HasColumnType("int");

                    b.Property<decimal>("NetWeightG")
                        .HasColumnType("decimal(18,3)");

                    b.Property<int>("PurityKarat")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("StoneAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("StoneWeightG")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("TagNo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<int>("WastageType")
                        .HasColumnType("int");

                    b.Property<decimal>("WastageValue")
                        .HasColumnType("decimal(18,3)");

                    b.HasKey("Id");

                    b.HasIndex("TagNo")
                        .IsUnique();

                    b.ToTable("StockTags");
                });

            modelBuilder.Entity("Billing_System.Models.ExchangeLine", b =>
                {
                    b.HasOne("Billing_System.Models.Invoice", "Invoice")
                        .WithMany("ExchangeLines")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Billing_System.Models.Invoice", b =>
                {
                    b.HasOne("Billing_System.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId");

                    b.HasOne("Billing_System.Models.GoldRate", "GoldRate")
                        .WithMany()
                        .HasForeignKey("GoldRateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("GoldRate");
                });

            modelBuilder.Entity("Billing_System.Models.InvoiceLine", b =>
                {
                    b.HasOne("Billing_System.Models.Invoice", "Invoice")
                        .WithMany("Lines")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Billing_System.Models.StockTag", "StockTag")
                        .WithMany()
                        .HasForeignKey("StockTagId");

                    b.Navigation("Invoice");

                    b.Navigation("StockTag");
                });

            modelBuilder.Entity("Billing_System.Models.Invoice", b =>
                {
                    b.Navigation("ExchangeLines");

                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
