using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace Billing_System.Services.Invoices;

public sealed class QuestPdfInvoiceGenerator : IInvoicePdfGenerator
{
    public byte[] Generate(InvoiceData data)
    {
        QuestPDF.Settings.License = LicenseType.Community;

        var doc = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(32);
                page.DefaultTextStyle(x => x.FontSize(11));

                page.Header().Column(col =>
                {
                    col.Item().Text(data.BusinessName).FontSize(18).SemiBold();
                    col.Item().Text($"Invoice / Bill #{data.BillId}").FontSize(12).SemiBold();
                    col.Item().Text($"Date: {data.Date:dd-MMM-yyyy HH:mm}");
                    if (!string.IsNullOrWhiteSpace(data.CustomerName))
                        col.Item().Text($"Customer: {data.CustomerName}");
                });

                page.Content().PaddingTop(16).Column(col =>
                {
                    col.Item().Table(table =>
                    {
                        table.ColumnsDefinition(cols =>
                        {
                            cols.RelativeColumn(6);
                            cols.RelativeColumn(2);
                            cols.RelativeColumn(2);
                            cols.RelativeColumn(2);
                        });

                        table.Header(header =>
                        {
                            header.Cell().Element(CellHeader).Text("Item");
                            header.Cell().Element(CellHeader).AlignRight().Text("Qty");
                            header.Cell().Element(CellHeader).AlignRight().Text("Price");
                            header.Cell().Element(CellHeader).AlignRight().Text("Total");

                            static IContainer CellHeader(IContainer c) =>
                                c.DefaultTextStyle(x => x.SemiBold().FontColor(Colors.White))
                                 .Background(Colors.Blue.Medium)
                                 .PaddingVertical(6)
                                 .PaddingHorizontal(8);
                        });

                        foreach (var line in data.Lines)
                        {
                            table.Cell().Element(CellBody).Text(line.Name);
                            table.Cell().Element(CellBody).AlignRight().Text(line.Quantity.ToString());
                            table.Cell().Element(CellBody).AlignRight().Text($"₹{line.UnitPrice:0.##}");
                            table.Cell().Element(CellBody).AlignRight().Text($"₹{line.LineTotal:0.##}");
                        }

                        static IContainer CellBody(IContainer c) =>
                            c.BorderBottom(1)
                             .BorderColor(Colors.Grey.Lighten2)
                             .PaddingVertical(6)
                             .PaddingHorizontal(8);
                    });

                    col.Item().PaddingTop(16).AlignRight().Column(totals =>
                    {
                        totals.Item().Row(r =>
                        {
                            r.RelativeItem().AlignRight().Text("Subtotal:");
                            r.ConstantItem(120).AlignRight().Text($"₹{data.Subtotal:0.##}").SemiBold();
                        });

                        totals.Item().Row(r =>
                        {
                            r.RelativeItem().AlignRight().Text($"GST ({data.GstRate:P0}):");
                            r.ConstantItem(120).AlignRight().Text($"₹{data.GstAmount:0.##}").SemiBold();
                        });

                        totals.Item().PaddingTop(6).Row(r =>
                        {
                            r.RelativeItem().AlignRight().Text("Grand Total:").FontSize(12).SemiBold();
                            r.ConstantItem(120).AlignRight().Text($"₹{data.GrandTotal:0.##}").FontSize(12).SemiBold();
                        });
                    });
                });

                page.Footer().AlignCenter().Text("Generated by Billing System")
                    .FontSize(10)
                    .FontColor(Colors.Grey.Darken1);
            });
        });

        return doc.GeneratePdf();
    }
}

